name: Translate README

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run README AI Translator Action
        uses: nobu007/readmeai_auto_action@v1.0.12
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ github.token }}
        with:
          repo: 'https://github.com/nobu007/YamlGuardian'  # 対象リポジトリのURL
          language: 'ja,en'  # 生成する言語（例: ja, en）
          exclude: 'node_modules,dist'  # 除外するファイルやディレクトリ
